project_id = "rwkgzppyjqklnylvqxos"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-onesignal-notification]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true